// This file is automatically generated. Do not edit it directly.
// NOTE: Auth is handled by Clerk, not Supabase. Session persistence is disabled.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { config } from '@/config/environment';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Auth is managed by Clerk - disable Supabase's built-in auth to prevent
// double sign-in prompts and session conflicts
export const supabase = createClient<Database>(config.supabase.url, config.supabase.anonKey, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
  }
});
